<?php
/**
 * @file
 * Modulos para el envio de emails 
 * 
 */

/**
 * Implementando Hook_menu() para 
 * mailfish
 */
function mailfish_menu() {
	$items = array();
	$items['admin/config/content/mailfish'] = array(
		'title' => 'Administracion',
		'description' => 'Menu de administracion',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('mailfish_admin_settings_form'),
		'access arguments' => array('administer mailfish subscription'),
		'file' => 'mailfish.admin.inc'
	);
	$items['admin/reports/mailfish'] = array(
        'title' => 'Reportes de Mailfish',
        'description' => 'Seccion de reportes de suscriptores de mailfish',
        'page callback' => 'mailfish_signups',
        'access arguments' => array('view mailfish subscription'),
        'file' => 'mailfish.admin.inc'
	);
	/*$items['node/%/subscribe'] = array(
		'title' => 'Subscribe',
		'description' => 'Suscribir a este nodo',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('mailfish_email_form', 1),
		'access arguments' => array('create mailfish subscription'),
		'type' => MENU_LOCAL_TASK,
	);*/
	return $items;
}

/**
 * Funcion para definir un formulario
 */
function mailfish_email_form($form, $form_state, $nid = 0) {
	global $user;
	$form = array();

	$form['email'] = array(
		'#title' => t('Email address'),
		'#type' => 'textfield',
		'#size' => 20,
		'#description' => t('Lista de emails'),
		'#required' => TRUE,
		'#default_value' => isset($user->mail) ? $user->mail : '',
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Suscribirse'),
	);
	
	$form['nid'] = array(
		'#type' => 'hidden',
		'#value' => $nid,
	);

	return $form;
}

/**
 * Implementacion de funcion de validacion para formulario
 */
function mailfish_email_form_validate($form, &$form_state) {
	$email = $form_state['values']['email'];
	if (!valid_email_address($email)) {
		$message = t('La direccion de correo electonico %email, no es valida!', 
			array('%email' => $email));
		form_set_error('email', $message);
	} // end if
    // Validando si el email existe
    $resultado = db_query('SELECT mail FROM {mailfish} WHERE mail = :email AND nid = :nid', 
                   array(':email' => $form_state['values']['email'], 
                         ':nid' => $form_state['values']['nid']))->fetchAll();
    if (!empty($resultado)) {
      form_set_error('email', t('El correo %email ya existe', 
      	array('%email' => $form_state['values']['email'])));
    } // end if
	return TRUE;
}

/**
 *
 */
function mailfish_email_form_submit($form, &$form_state) {
   //dpm($form_state);
   global $user;
   $fields = array(
     'nid' => $form_state['values']['nid'],
     'uid' => $user->uid,
     'mail' => $form_state['values']['email'],
     'created' => REQUEST_TIME
   );
   
   $insert = db_insert('mailfish');
   $insert->fields($fields);
   $result = $insert->execute();
   drupal_set_message(t('ID de confirmacion: %id', 
   	array('%id' => $result)), 'status');

}

/**
* Implementando hook_permission()
*/
function mailfish_permission() {
  $perm = array(
	  'view mailfish subscription' => array(
	  	'title' => t('View Mailfish Subscription'),
	  ),
	  'create mailfish subscription' => array(
	  	'title' => t('Create Mailfish Subscription'),
	  ),
	  'manage mailfish subscription' => array(
	  	'title' => t('Manage Mailfish Subscription'),
	  ),
	  'administer mailfish subscription' => array(
	  	'title' => t('Administer Mailfish Subscription'),
	  ),
  );
  return $perm;
}

/**
 * Implementando hook_block_info
 */
function mailfish_block_info() {
	$blocks = array();
	$blocks['mailfish_subscribe'] = array(
		'info' => t('Mailfish Sign Up Form'),
	);

	return $blocks;
}

/**
 * Implementando hook_block_view
 */
function mailfish_block_view($delta) {
	$block = array();
	switch ($delta) {
		case 'mailfish_subscribe':
			if (arg(0) == 'node' && is_numeric(arg(1))) {
				$nid = arg(1);
				$node = node_load($nid);
				$types = variable_get('mailfish_check_form_api', array());
				watchdog('mailfish', '%watchdog', array('%watchdog' => print_r($types, TRUE)), WATCHDOG_DEBUG);
				if (!empty($types[$node->type])) {
				  $form = drupal_get_form('mailfish_email_form', $nid);
				  $block = array(
					  'subject' => t('Formulario de logueo para este nodo!'),
					  'content' => theme('mailfish_block', 
						array('rendered_form' => drupal_render($form))),
				  );
				} // end if
			} // end if
			break;

	} // end switch

	return $block;
}

/**
 * Implementando hook_theme()
 */
function mailfish_theme() {
	$theme = array();
	$theme['mailfish_block'] = array(
		'variables' => array(
			'rendered_form' => '',
		),
		'template' => 'mailfish-block',
	);

	return $theme;
}
