<?php
/**
* @file 
* Archivo que define la funcionalidad de un boton que permite eliminar nodos
*/

/**
* Implementando el hook_node_view()
*/
function redbutton_node_view($node, $view_mode) { 
	$node->content['redbutton'] = array(); 
	if ($node->type == 'listas') {
		$node->content['redbutton']['#markup'] = l('Eliminar', 'node/' . $node->nid . '/delete', 
		    array('attributes' => array('style' => 'color:red')));
	} // end if  
	dpm($node);
} 
/**
 * Implementando hook_init
 */
function redbutton_init() {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $path = drupal_get_path('module', 'redbutton');
    drupal_add_js($path . '/js/redbutton.js');
  } // end if
}